# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import piper_pb2 as piper__pb2


class PiperModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TextToSpeech = channel.stream_stream(
                '/pkg.PiperModel/TextToSpeech',
                request_serializer=piper__pb2.TextToSpeechRequest.SerializeToString,
                response_deserializer=piper__pb2.TextToSpeechResponse.FromString,
                )


class PiperModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TextToSpeech(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PiperModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TextToSpeech': grpc.stream_stream_rpc_method_handler(
                    servicer.TextToSpeech,
                    request_deserializer=piper__pb2.TextToSpeechRequest.FromString,
                    response_serializer=piper__pb2.TextToSpeechResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pkg.PiperModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PiperModel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TextToSpeech(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/pkg.PiperModel/TextToSpeech',
            piper__pb2.TextToSpeechRequest.SerializeToString,
            piper__pb2.TextToSpeechResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
