# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import whisper_pb2 as whisper__pb2


class WhisperModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SpeechToText = channel.stream_stream(
                '/pkg.WhisperModel/SpeechToText',
                request_serializer=whisper__pb2.SpeechToTextRequest.SerializeToString,
                response_deserializer=whisper__pb2.SpeechToTextResponse.FromString,
                )


class WhisperModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SpeechToText(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WhisperModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SpeechToText': grpc.stream_stream_rpc_method_handler(
                    servicer.SpeechToText,
                    request_deserializer=whisper__pb2.SpeechToTextRequest.FromString,
                    response_serializer=whisper__pb2.SpeechToTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pkg.WhisperModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WhisperModel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SpeechToText(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/pkg.WhisperModel/SpeechToText',
            whisper__pb2.SpeechToTextRequest.SerializeToString,
            whisper__pb2.SpeechToTextResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
